In [1]:
import tensorflow as tf

In [2]:
from tensorflow import keras
from tensorflow.keras.layers import Dense

In [3]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

# Sample Data Creation and Pre-Processing

In [4]:
train_labels = []
train_samples = []

In [5]:
for i in range(50):
    # 5% of younger individuals who experienced side effects:
    random_younger = randint(13, 64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    # 5% of older individuals who did not experience side effects:
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)
    
for i in range(1000):
    # 95% of younger individuals who did not experience side effects:
    random_younger = randint(13, 64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    # 95% of older individuals who experienced side effects:
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)   

In [6]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)

train_labels, train_samples = shuffle(train_labels, train_samples)

In [7]:
scaler = MinMaxScaler()
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [8]:
scaled_train_samples

array([[0.44827586],
       [0.6091954 ],
       [0.88505747],
       ...,
       [0.45977011],
       [0.31034483],
       [0.49425287]])

In [9]:
train_labels.shape

(2100,)

# Simple tk.keras Sequential Model

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [24]:
model = Sequential([
    Dense(units = 16, input_shape = (1,), activation = 'relu'),
    Dense(units = 32, activation = 'relu'),
    Dense(units = 2, activation = 'softmax')
])

In [25]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_7 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_8 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.compile(optimizer = Adam(learning_rate = 0.001), loss = 'sparse_categorical_crossentropy',
              metrics = ['accuracy'] )

In [27]:
model.fit(x = scaled_train_samples, y = train_labels, validation_split = 0.1, batch_size = 10, epochs = 30,
          shuffle = True, verbose = 2)

Epoch 1/30
189/189 - 0s - loss: 0.5925 - accuracy: 0.7370 - val_loss: 0.4368 - val_accuracy: 0.9095
Epoch 2/30
189/189 - 0s - loss: 0.2774 - accuracy: 0.9423 - val_loss: 0.1932 - val_accuracy: 0.9667
Epoch 3/30
189/189 - 0s - loss: 0.1365 - accuracy: 0.9783 - val_loss: 0.1189 - val_accuracy: 0.9810
Epoch 4/30
189/189 - 0s - loss: 0.0915 - accuracy: 0.9862 - val_loss: 0.0942 - val_accuracy: 0.9667
Epoch 5/30
189/189 - 0s - loss: 0.0721 - accuracy: 0.9894 - val_loss: 0.0784 - val_accuracy: 0.9667
Epoch 6/30
189/189 - 0s - loss: 0.0595 - accuracy: 0.9899 - val_loss: 0.0780 - val_accuracy: 0.9476
Epoch 7/30
189/189 - 0s - loss: 0.0519 - accuracy: 0.9947 - val_loss: 0.0629 - val_accuracy: 0.9810
Epoch 8/30
189/189 - 0s - loss: 0.0458 - accuracy: 0.9942 - val_loss: 0.0570 - val_accuracy: 0.9810
Epoch 9/30
189/189 - 0s - loss: 0.0414 - accuracy: 0.9958 - val_loss: 0.0607 - val_accuracy: 0.9667
Epoch 10/30
189/189 - 0s - loss: 0.0390 - accuracy: 0.9926 - val_loss: 0.0612 - val_accuracy: 0.9667

# Test Set

In [28]:
test_labels = []
test_samples = []

In [29]:
for i in range(10):
    # 5% of younger individuals who experienced side effects:
    random_younger = randint(13, 64)
    test_samples.append(random_younger)
    test_labels.append(1)
    
    # 5% of older individuals who did not experience side effects:
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)
    
for i in range(210):
    # 95% of younger individuals who did not experience side effects:
    random_younger = randint(13, 64)
    test_samples.append(random_younger)
    test_labels.append(1)
    
    # 95% of older individuals who experienced side effects:
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)   

In [30]:
test_labels = np.array(test_labels)
test_samples = np.array(test_samples)

test_labels, test_samples = shuffle(test_labels, test_samples)

In [31]:
scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1,1))

# Predict

In [32]:
predictions = model.predict(scaled_test_samples, batch_size = 10, verbose = 0)

In [33]:
print(predictions)

[[1.18512884e-01 8.81487131e-01]
 [9.99996901e-01 3.09040797e-06]
 [1.43490880e-07 9.99999881e-01]
 [1.00000000e+00 3.13822532e-08]
 [1.23766014e-07 9.99999881e-01]
 [2.04658363e-06 9.99997973e-01]
 [5.76754034e-01 4.23245937e-01]
 [1.47798048e-07 9.99999881e-01]
 [1.00000000e+00 9.96209426e-09]
 [2.04658363e-06 9.99997973e-01]
 [9.99999762e-01 2.12441833e-07]
 [9.99999523e-01 4.56522002e-07]
 [8.72878019e-08 9.99999881e-01]
 [9.99999881e-01 9.88591040e-08]
 [1.00000000e+00 4.60038478e-08]
 [9.99515295e-01 4.84655669e-04]
 [1.56804148e-07 9.99999881e-01]
 [9.99091625e-01 9.08365473e-04]
 [9.99985695e-01 1.42710569e-05]
 [9.99985695e-01 1.42710569e-05]
 [9.99969363e-01 3.06669644e-05]
 [9.99955058e-01 4.49547806e-05]
 [9.52819121e-08 9.99999881e-01]
 [9.52819121e-08 9.99999881e-01]
 [8.72878019e-08 9.99999881e-01]
 [1.29107284e-04 9.99870896e-01]
 [9.99999881e-01 9.88591040e-08]
 [1.00644854e-07 9.99999881e-01]
 [8.53982698e-08 9.99999881e-01]
 [4.05567735e-05 9.99959469e-01]
 [9.977147

In [34]:
rounded_predictions = np.argmax(predictions, axis = 1)

# Confusion Matrix

In [35]:
from sklearn.metrics import confusion_matrix, plot_confusion_matrix

In [37]:
confusion_matrix(test_labels, rounded_predictions)

array([[220,   0],
       [  0, 220]])

# Save and Load a Model with TensorFlow API

In [42]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_7 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_8 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


## 1. model.save method

In [43]:
# 1. model.save
model.save('firstkerasmodel.h5') # Saves the weights, architecture, optimizers, and state of training. (Saves everything)

In [45]:
from tensorflow.keras.models import load_model

new_model = load_model('firstkerasmodel.h5')

new_model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_7 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_8 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [48]:
new_model.get_weights()

[array([[-0.55716085, -0.32203937,  0.86739695,  0.61707467,  0.33897573,
          0.8232959 , -0.11613718,  0.7995564 , -0.5808564 , -0.04961455,
          0.72767866, -0.37515175, -0.18670452, -0.41478625,  0.7647245 ,
         -0.08623576]], dtype=float32),
 array([ 0.        ,  0.        , -0.34881154, -0.29884645,  0.5218074 ,
        -0.3475647 ,  0.        , -0.20423543,  0.        ,  0.        ,
        -0.31785813,  0.        ,  0.        ,  0.        , -0.3235055 ,
         0.        ], dtype=float32),
 array([[-1.97299004e-01,  2.04568893e-01, -2.87829429e-01,
          2.01653093e-01, -1.63130552e-01, -1.22712314e-01,
          3.37720603e-01, -1.78275526e-01, -1.58849195e-01,
         -1.90032884e-01,  9.40543115e-02,  1.81744546e-01,
          2.27755636e-01,  2.84398228e-01, -1.05370075e-01,
         -3.10701936e-01,  2.08688110e-01, -1.26816496e-01,
         -1.61251739e-01, -9.12406743e-02,  1.72423154e-01,
         -3.12845767e-01, -1.56568035e-01, -1.55085400e-01,
 

In [50]:
new_model.optimizer

## 2. model.to_json method

In [51]:
# Saves only the architecture

json_string = model.to_json()

In [52]:
json_string

'{"class_name": "Sequential", "config": {"name": "sequential_2", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 1], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_6_input"}}, {"class_name": "Dense", "config": {"name": "dense_6", "trainable": true, "batch_input_shape": [null, 1], "dtype": "float32", "units": 16, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_7", "trainable": true, "dtype": "float32", "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "

In [53]:
from tensorflow.keras.models import model_from_json

model_architecture = model_from_json(json_string)

model_architecture.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_7 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_8 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


## 3. model.save_weights() method

In [54]:
model.save_weights('firstkerasmodel_weights.h5')

In [59]:
model2 = Sequential([
    Dense(units = 16, input_shape = (1,), activation = 'relu'),
    Dense(units = 32, activation = 'relu'),
    Dense(units = 2, activation = 'softmax')
])

In [60]:
model2.get_weights()

[array([[-0.39162442,  0.11724764, -0.25442442, -0.00225478,  0.35998958,
         -0.23925671,  0.03585947,  0.5235784 ,  0.0245896 ,  0.21380568,
          0.13157755, -0.58754146, -0.22811162,  0.5205792 ,  0.3437305 ,
         -0.01214182]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32),
 array([[-0.2728044 , -0.28303918, -0.06303972,  0.04569924, -0.3043594 ,
          0.2735454 , -0.23211896,  0.09998101,  0.29245546, -0.0964663 ,
         -0.3207569 , -0.08666438, -0.15080951,  0.09104091, -0.0154705 ,
          0.18042377, -0.04396489,  0.223901  , -0.33447206, -0.33211192,
          0.33777764, -0.16438915, -0.04048288,  0.2862474 ,  0.3205239 ,
         -0.20949732,  0.17962399, -0.15460189, -0.01802081,  0.14067742,
          0.19975308, -0.25644672],
        [ 0.02530858,  0.10904688,  0.17199662,  0.24327204, -0.19723628,
          0.2413421 , -0.07125229,  0.03094953,  0.04949769, -0.28785226,
         -0.06

In [61]:
model2.load_weights('firstkerasmodel_weights.h5')

In [62]:
model2.get_weights()

[array([[-0.55716085, -0.32203937,  0.86739695,  0.61707467,  0.33897573,
          0.8232959 , -0.11613718,  0.7995564 , -0.5808564 , -0.04961455,
          0.72767866, -0.37515175, -0.18670452, -0.41478625,  0.7647245 ,
         -0.08623576]], dtype=float32),
 array([ 0.        ,  0.        , -0.34881154, -0.29884645,  0.5218074 ,
        -0.3475647 ,  0.        , -0.20423543,  0.        ,  0.        ,
        -0.31785813,  0.        ,  0.        ,  0.        , -0.3235055 ,
         0.        ], dtype=float32),
 array([[-1.97299004e-01,  2.04568893e-01, -2.87829429e-01,
          2.01653093e-01, -1.63130552e-01, -1.22712314e-01,
          3.37720603e-01, -1.78275526e-01, -1.58849195e-01,
         -1.90032884e-01,  9.40543115e-02,  1.81744546e-01,
          2.27755636e-01,  2.84398228e-01, -1.05370075e-01,
         -3.10701936e-01,  2.08688110e-01, -1.26816496e-01,
         -1.61251739e-01, -9.12406743e-02,  1.72423154e-01,
         -3.12845767e-01, -1.56568035e-01, -1.55085400e-01,
 